### Create border array
#### Description: Given a single integer n, create an (n x n) 2D array with 1 on the border and 0 on the inside.

Note: Make sure the array is of type int.<br>

Example:<br>
Input 1:<br>
4<br>
Output 1:<br>
[[1 1 1 1]<br>
[1 0 0 1]<br>
[1 0 0 1]<br>
[1 1 1 1]]<br>
Input 2:<br>
2<br>
Output 2:<br>
[[1 1] <br>
 [1 1]] <br>

Execution time limit<br>
15 seconds<br>

In [1]:
# Read the variable from STDIN
n = int(input())

import numpy as np

array = np.zeros((n,n), dtype = 'int')

array[0] = np.ones(n, dtype = 'int')
array[:,0] = 1
array[-1] = np.ones(n, dtype = 'int')
array[:,-1] = 1

print(array)

 11


[[1 1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1 1]]
