### 1. hstack and vstack:

In lists whenever we do the operation list1 + list2, we observe concatenation of 2 arrays.<br>
But in arrays the list elements adds itself <br>
Now suppose we want to concatenate 2 arrays.. how do we do that?<br>
In arrays we have 2 different ways of doing it:
1. hstck: horizontal concatenation
2. vstack: vertical concatenation

In [1]:
import numpy as np

In [2]:
arr_1 = np.arange(5)
arr_2 = np.arange(5,10)
arr_3 = np.array(['Souvik', 'Sayli', 'Sumita', 'Debdas', 'Ganguly'])

print(f"1st array: {arr_1}")
print(f"2nd array: {arr_2}")
print(f"3rd array: {arr_3}")

1st array: [0 1 2 3 4]
2nd array: [5 6 7 8 9]
3rd array: ['Souvik' 'Sayli' 'Sumita' 'Debdas' 'Ganguly']


In [3]:
print(f"Simple + operator between the 2 arrays: {arr_1 + arr_2}")

Simple + operator between the 2 arrays: [ 5  7  9 11 13]


In [4]:
arr_hstack_diff_datatype = np.hstack((arr_1, arr_2, arr_3), dtype=object)

arr_hstack_no_dtype = np.hstack((arr_1, arr_2, arr_3))

arr_hstack_same_datatype = np.hstack((arr_1, arr_2))


print(arr_hstack_diff_datatype)
print("\n")
print(arr_hstack_no_dtype)
print("\n")
print(arr_hstack_same_datatype)

[0 1 2 3 4 5 6 7 8 9 'Souvik' 'Sayli' 'Sumita' 'Debdas' 'Ganguly']


['0' '1' '2' '3' '4' '5' '6' '7' '8' '9' 'Souvik' 'Sayli' 'Sumita'
 'Debdas' 'Ganguly']


[0 1 2 3 4 5 6 7 8 9]


In [5]:
arr_vstack_diff_datatype = np.vstack((arr_1, arr_2, arr_3), dtype=object)

arr_vstack_no_dtype = np.vstack((arr_1, arr_2, arr_3))

arr_vstack_same_datatype = np.vstack((arr_1, arr_2))


print(arr_vstack_diff_datatype)
print("\n")
print(arr_vstack_no_dtype)
print("\n")
print(arr_vstack_same_datatype)

[[0 1 2 3 4]
 [5 6 7 8 9]
 ['Souvik' 'Sayli' 'Sumita' 'Debdas' 'Ganguly']]


[['0' '1' '2' '3' '4']
 ['5' '6' '7' '8' '9']
 ['Souvik' 'Sayli' 'Sumita' 'Debdas' 'Ganguly']]


[[0 1 2 3 4]
 [5 6 7 8 9]]


### 2. reshape:

This function is used to manipulate the dimensions and shape of the array. 

In [6]:
arr_4 = np.random.randint(1, 99, size = (11,10))

arr_4

array([[37, 23,  7, 80, 20, 45,  7, 12, 20, 93],
       [16, 15, 65, 41, 67, 46, 68, 40, 90, 20],
       [ 5, 76, 55, 41, 44, 68, 60,  4, 67, 60],
       [50, 89, 77, 77, 85,  3, 48, 34, 41, 89],
       [65, 14, 54, 34, 12, 69,  4, 21, 63, 68],
       [53,  7, 74, 57, 48,  8, 87, 79, 73, 59],
       [63, 33,  4, 34, 36, 22, 25, 93,  6, 65],
       [83, 51, 84, 64, 64, 42, 12, 86, 46, 31],
       [33, 32, 61, 16, 28, 30, 77, 73, 63, 62],
       [60, 45, 97, 77, 70, 95, 40, 34, 30, 33],
       [63,  1, 88, 62, 58, 90, 23, 11, 92, 51]])

In [8]:
arr_4.shape

(11, 10)

In [11]:
arr_4 = arr_4.reshape((55,2))

arr_4

array([[37, 23],
       [ 7, 80],
       [20, 45],
       [ 7, 12],
       [20, 93],
       [16, 15],
       [65, 41],
       [67, 46],
       [68, 40],
       [90, 20],
       [ 5, 76],
       [55, 41],
       [44, 68],
       [60,  4],
       [67, 60],
       [50, 89],
       [77, 77],
       [85,  3],
       [48, 34],
       [41, 89],
       [65, 14],
       [54, 34],
       [12, 69],
       [ 4, 21],
       [63, 68],
       [53,  7],
       [74, 57],
       [48,  8],
       [87, 79],
       [73, 59],
       [63, 33],
       [ 4, 34],
       [36, 22],
       [25, 93],
       [ 6, 65],
       [83, 51],
       [84, 64],
       [64, 42],
       [12, 86],
       [46, 31],
       [33, 32],
       [61, 16],
       [28, 30],
       [77, 73],
       [63, 62],
       [60, 45],
       [97, 77],
       [70, 95],
       [40, 34],
       [30, 33],
       [63,  1],
       [88, 62],
       [58, 90],
       [23, 11],
       [92, 51]])