### Numpy vs List

#### 1. We cannot perform a mathematical operation on all the elements of a list together. It gives an error as shown below:

In [1]:
sample_list = [1, 2, 3]

sample_list * 2.5

TypeError: can't multiply sequence by non-int of type 'float'

In [2]:
import numpy as np

sample_np_array = np.array([1, 2, 3])

sample_np_array * 2.5

array([2.5, 5. , 7.5])

This can be achieved using numpy. The key advantage of NumPy arrays over lists is that the array allows you to operate over the entire data, unlike lists. 

An important thing to note is that the above array is a one-dimensional array. We can also create multidimensional arrays in the coming lectures.

Numpy array can also br created using a tuple. 

#### Any sequence that has an array-like structure can be passed to the np.array function.

In [15]:
print(np.array((4, 7, 9, "Souvik")))

['4' '7' '9' 'Souvik']


#### 2. Numpy arrays are homogeneous in nature. They can contain data only of a single data type

In [3]:
np.array([1, "sample_string", True])

array(['1', 'sample_string', 'True'], dtype='<U21')

Every element is converted to a string

In [10]:
np.array([1, 1.5, 3.4, False])

array([1. , 1.5, 3.4, 0. ])

Every element is converted to float

#### 3. Difference between operations of lists and numpy array

In [7]:
l1 = [1,2,3]
l2 = [4,5,6]

print(l1+l2)

[1, 2, 3, 4, 5, 6]


In [6]:
np_1 = np.array([1,2,3])
np_2 = np.array([4,5,6])

print(np_1 + np_2)

[5 7 9]
