### Border Rows and Columns

#### Description :Extract all the border rows and columns from a 2-D array.

#### Format:
Input: A 2-D Python list <br>
Output: Four NumPy arrays - First column of the input array, first row of the input array, last column of the input array, last row of the input array respectively. <br>

Example: <br>
Input 1: <br>
[[11 12 13 14] <br>
 [21 22 23 24] <br>
 [31 32 33 34]] <br><br>
Output 1: <br>
[11 21 31] <br>
[11 12 13 14] <br>
[14 24 34] <br>
[31 32 33 34] <br>
Execution time limit

In [8]:
# Read the input list
import ast,sys
input_list = [[11, 12, 13, 14],[21, 22, 23, 24],[31, 32, 33, 34]]

import numpy as np

# Convert the input list to a NumPy array
array_2d =np.array(input_list)

# Extract the first column, first row, last column and last row respectively using
# appropriate indexing
col_first = array_2d[:,0]
row_first = array_2d[0]
col_last = array_2d[:, -1]
row_last = array_2d[-1]

print(col_first)
print(row_first)
print(col_last)
print(row_last)

[11 21 31]
[11 12 13 14]
[14 24 34]
[31 32 33 34]
